### ISSUE TITLE
Plugin not detecting BBT citekey

### ISSUE THREAD

**Issue by sati-bodhi** [benjypng/logseq-zoterolocal-plugin#36]
<img width="2416" height="1353" alt="Image" src="https://github.com/user-attachments/assets/23a0955b-8e13-49dc-883f-558458275505" />

Cite Key is N/A even though search captures the citekey string. Insertion failed with `Cite key is not configured properly in BetterBibTex`.

**Comment by ferBV** [comment]
I found the issue, logseq plugin requires that the citekey is fixed, which  according to the BBT documentation it means adding the citekey to the "extra" field, this can be done automatically for new items if your check automatically pin citation key in advanced BBT settings, however old items are not updated automatically, but you can do it by selecting all items and with right click and select Generate BibTeX key.
  
https://retorque.re/zotero-better-bibtex/citing/

Maybe this should be in the README.md

**Comment by CousinThrockmorton** [comment]
I have the same issue however I am a bit confused as I can't find a "Generate BibTeX key" option. I don't use InspireHEP so that is also confusing. But neither option seem to add the citekeys whether newly added or old to the 'extra' field. I have Zotero 8 and BBT 8.0.14.

<img width="1920" height="1080" alt="Image" src="https://github.com/user-attachments/assets/d05233b4-a7cc-4d03-a2b9-96bbbce8b36a" />

**Comment by dag2108** [comment]
Anybody have any luck getting past this error? I just upgraded to the latest version of BBT (8.0.41) that came out today and I'm still getting "Citation key not configured properly in Better BibTex" whenever I try to import an item into Logseq. I'm running Zotero 9 beta.
